/* ELIMINACION DE TABLAS */

DROP TABLE Transferencia CASCADE;
DROP TABLE Ingreso CASCADE;
DROP TABLE Retirada CASCADE;
DROP TABLE Posee CASCADE;
DROP TABLE Cliente CASCADE;
DROP TABLE Oficina CASCADE;
DROP TABLE CuentaCorriente CASCADE;
DROP TABLE CuentaAhorro CASCADE;
DROP TABLE Cuenta CASCADE;
DROP TABLE Operacion CASCADE;

/* CREACION DE TABLAS */

CREATE TABLE Cliente(
	nombre	VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	DNI VARCHAR(10) PRIMARY KEY,
	edad INTEGER NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	email VARCHAR(100),
	telefono INTEGER NOT NULL
);

CREATE TABLE Cuenta(
	IBAN VARCHAR(150) PRIMARY KEY,
	numero INTEGER NOT NULL,
	saldo DECIMAL(10,2) NOT NULL,
	fechaCreacion DATE NOT NULL
);

CREATE TABLE Posee(
	DNI VARCHAR(10) NOT NULL,
	IBAN VARCHAR(150) NOT NULL,
	PRIMARY KEY (DNI,IBAN),
	FOREIGN KEY (DNI) REFERENCES Cliente(DNI),
	FOREIGN KEY (IBAN)	REFERENCES Cuenta(IBAN)
);

CREATE TABLE Oficina(
	codigo VARCHAR(10) PRIMARY KEY,
	direccion VARCHAR(50) NOT NULL,
	telefono VARCHAR(10) NOT NULL
);

CREATE TABLE CuentaCorriente(
	oficina VARCHAR(10) REFERENCES Oficina(codigo) NOT NULL
) INHERITS (Cuenta);

CREATE TABLE CuentaAhorro(
  interes DECIMAL(3,2) NOT NULL
) INHERITS (Cuenta);


CREATE TABLE Operacion(
  codigo VARCHAR(150) NOT NULL,
	IBANOrigen VARCHAR(150) NOT NULL,
	fecha DATE NOT NULL,
	hora VARCHAR(8) NOT NULL,
	cantidad DECIMAL(10,2) NOT NULL,
	descripcion VARCHAR(400),
	PRIMARY KEY (codigo, IBANOrigen),
	FOREIGN KEY (IBANOrigen) REFERENCES Cuenta(IBAN)
);

CREATE TABLE Transferencia(
    IBANDestino VARCHAR(150) NOT NULL,
		FOREIGN KEY (IBANDestino) REFERENCES Cuenta(IBAN)
) INHERITS (Operacion);

CREATE TABLE Ingreso(
    oficina VARCHAR(15),
		FOREIGN KEY (oficina) REFERENCES Oficina(codigo)
) INHERITS (Operacion);

CREATE TABLE Retirada(
    oficina VARCHAR(15),
		FOREIGN KEY (oficina) REFERENCES Oficina(codigo)
) INHERITS(Operacion);
