-- DROP DE TABLES

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE Posee';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE Retirada';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE Ingreso';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE Transferencia';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE Operacion';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE CuentaCorriente';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE CuentaAhorro';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE Oficina';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE Cuenta';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TABLE Cliente';--
END;

-- DROP TYPES

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE PoseeUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE RetiradaUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE IngresoUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE TransferenciaUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE OperacionUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE CuentaCorrienteUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE CuentaAhorroUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE OficinaUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE CuentaUdt';--
END;

BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
BEGIN END;--
EXECUTE IMMEDIATE 'DROP TYPE ClienteUdt';--
END;

-- CREACION DE TIPOS

CREATE TYPE ClienteUdt AS(
	nombre	VARCHAR(100),
	apellido VARCHAR(100),
	DNI VARCHAR(10),
	edad INTEGER,
	direccion VARCHAR(100),
	email VARCHAR(100),
	telefono VARCHAR(20)
) MODE DB2SQL;

CREATE TYPE CuentaUdt AS(
	IBAN VARCHAR(150),
	numero INTEGER,
	saldo DECIMAL(10,2),
	fechaCreacion DATE
) MODE DB2SQL;


CREATE TYPE PoseeUdt AS(
	cliente ref(ClienteUdt),
	cuenta ref(CuentaUdt)
) MODE DB2SQL;

-- en operacion el ibanOrigen debe ser el var para que sea clave primaria

CREATE TYPE OperacionUdt AS(
  	codigo VARCHAR(150),
	ibanOrigen VARCHAR(150),
	fecha DATE,
	hora VARCHAR(8),
	cantidad DECIMAL(10,2),
	descripcion VARCHAR(400)
) MODE DB2SQL;


CREATE TYPE OficinaUdt AS(
  codigo VARCHAR(10),
  direccion VARCHAR(50),
  telefono VARCHAR(20)
) MODE DB2SQL;

CREATE TYPE CuentaCorrienteUdt UNDER CuentaUdt AS(
  oficina ref(OficinaUdt)
) MODE DB2SQL;

CREATE TYPE CuentaAhorroUdt UNDER CuentaUdt AS(
  interes DECIMAL(3,2)
) MODE DB2SQL;


CREATE TYPE TransferenciaUdt UNDER OperacionUdt AS(
    cuentaDestino ref(CuentaUdt)
) MODE DB2SQL;

CREATE TYPE IngresoUdt UNDER OperacionUdt AS(
	oficina ref(OficinaUdt)
) MODE DB2SQL;

CREATE TYPE RetiradaUdt UNDER OperacionUdt AS(
	oficina ref(OficinaUdt)
) MODE DB2SQL;

-- Creacion de tablas

CREATE TABLE Cliente OF ClienteUdt(
	REF IS oid USER GENERATED,
	nombre WITH OPTIONS NOT NULL,
	apellido WITH OPTIONS NOT NULL,
	DNI WITH OPTIONS NOT NULL PRIMARY KEY,
	edad WITH OPTIONS NOT NULL,
	direccion WITH OPTIONS NOT NULL,
	telefono WITH OPTIONS NOT NULL
);


CREATE TABLE Cuenta OF CuentaUdt(
	REF IS oid USER GENERATED,
	IBAN WITH OPTIONS NOT NULL PRIMARY KEY,
	numero WITH OPTIONS NOT NULL,
	saldo WITH OPTIONS NOT NULL,
	fechaCreacion WITH OPTIONS NOT NULL
);

CREATE TABLE Posee OF PoseeUdt(
	REF IS oid USER GENERATED,
	cliente WITH OPTIONS SCOPE Cliente,
	cuenta WITH OPTIONS SCOPE Cuenta
);


CREATE TABLE Oficina OF OficinaUdt(
  REF IS oid USER GENERATED,
  codigo WITH OPTIONS NOT NULL PRIMARY KEY,
  direccion WITH OPTIONS NOT NULL,
  telefono WITH OPTIONS NOT NULL
);


CREATE TABLE Operacion OF OperacionUdt(
	REF IS oid USER GENERATED,
  	codigo WITH OPTIONS NOT NULL,
	ibanOrigen WITH OPTIONS NOT NULL,
	fecha WITH OPTIONS NOT NULL,
	hora WITH OPTIONS NOT NULL,
	cantidad WITH OPTIONS NOT NULL,
	PRIMARY KEY (codigo, ibanOrigen)
);

CREATE TABLE CuentaCorriente OF CuentaCorrienteUdt UNDER Cuenta INHERIT SELECT PRIVILEGES(
  oficina WITH OPTIONS SCOPE Oficina
);

CREATE TABLE CuentaAhorro OF CuentaAhorroUdt UNDER Cuenta INHERIT SELECT PRIVILEGES(
  interes WITH OPTIONS NOT NULL
);


CREATE TABLE Transferencia OF TransferenciaUdt UNDER Operacion INHERIT SELECT PRIVILEGES(
	cuentaDestino WITH OPTIONS SCOPE Cuenta
);


CREATE TABLE Ingreso OF IngresoUdt UNDER Operacion INHERIT SELECT PRIVILEGES(
	oficina WITH OPTIONS SCOPE Oficina
);


CREATE TABLE Retirada OF RetiradaUdt UNDER Operacion INHERIT SELECT PRIVILEGES(
	oficina WITH OPTIONS SCOPE Oficina
);


