CREATE TABLE Cliente(
	DNI VARCHAR(10) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	edad DECIMAL(3,0) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	email VARCHAR(100),
	Telefono DECIMAL(15,0) NOT NULL,	
	PRIMARY KEY (DNI)
);

CREATE TABLE Oficina(
	codigo VARCHAR(15) NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	telefono DECIMAL(15,0) NOT NULL,
	PRIMARY KEY (codigo)
);

CREATE TABLE Cuenta(
	IBAN VARCHAR(150) NOT NULL,
	numero DECIMAL(50,0) NOT NULL,
	saldo DECIMAL(10,2) NOT NULL,
	fechaCreacion DATE NOT NULL,
	tipo VARCHAR(9) NOT NULL,
	interes DECIMAL(3,2),
	oficina VARCHAR(15),
	PRIMARY KEY(IBAN),
	FOREIGN KEY(oficina) REFERENCES Oficina(codigo)
);

CREATE TABLE Posee(
	DNI VARCHAR(10) NOT NULL,
	IBAN VARCHAR(150) NOT NULL,
	PRIMARY KEY (DNI,IBAN),
	FOREIGN KEY (DNI) REFERENCES Cliente(DNI),
	FOREIGN KEY (IBAN)	REFERENCES Cuenta(IBAN)
);
/*
CREATE TABLE Transferencia(
	codigo VARCHAR(150) NOT NULL,
	fecha DATE NOT NULL,
	hora VARCHAR(8) NOT NULL,
	cantidad DECIMAL(10,0) NOT NULL,
	descripcion VARCHAR(400),
	IBANOrigen VARCHAR(150) NOT NULL,
	IBANDestino VARCHAR(150) NOT NULL,
	PRIMARY KEY (codigo,IBANDestino),
	FOREIGN KEY (IBANOrigen) REFERENCES Cuenta(IBAN),
	FOREIGN KEY (IBANDestino) REFERENCES Cuenta(IBAN)
);

CREATE TABLE IngresoRetirada(
	codigo VARCHAR(150) NOT NULL,
	fecha DATE NOT NULL,
	hora VARCHAR(8) NOT NULL,
	cantidad DECIMAL(10,0) NOT NULL,
	descripcion VARCHAR(400),
    IBANOrigen VARCHAR(150) NOT NULL,
	IBANDestino VARCHAR(150) NOT NULL,
	oficina VARCHAR(15) NOT NULL,
	PRIMARY KEY (codigo,IBANDestino),
	FOREIGN KEY (IBANOrigen) REFERENCES Cuenta(IBAN),
	FOREIGN KEY (oficina) REFERENCES Oficina(codigo)
);
*/
CREATE TABLE Operacion(
	codigo VARCHAR(150) NOT NULL,
	fecha DATE NOT NULL,
	hora VARCHAR(8) NOT NULL,
	cantidad DECIMAL(10,0) NOT NULL,
	descripcion VARCHAR(400),
    IBANOrigen VARCHAR(150) NOT NULL,
	IBANDestino VARCHAR(150),
	oficina VARCHAR(15),
	PRIMARY KEY (codigo,IBANDestino),
	FOREIGN KEY (IBANOrigen) REFERENCES Cuenta(IBAN),
	FOREIGN KEY (IBANDestino) REFERENCES Cuenta(IBAN),
	FOREIGN KEY (oficina) REFERENCES Oficina(codigo)
);