/* ELIMINACION DE TABLAS */

DROP TABLE IF EXISTS Transferencia CASCADE;
DROP TABLE IF EXISTS Ingreso CASCADE;
DROP TABLE IF EXISTS Retirada CASCADE;
DROP TABLE IF EXISTS Posee CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
DROP TABLE IF EXISTS Oficina CASCADE;
DROP TABLE IF EXISTS CuentaCorriente CASCADE;
DROP TABLE IF EXISTS CuentaAhorro CASCADE;
DROP TABLE IF EXISTS Cuenta CASCADE;
DROP TABLE IF EXISTS Operacion CASCADE;

/* CREACION DE TABLAS */

CREATE TABLE Cliente(
	DNI VARCHAR(10) PRIMARY KEY,
	nombre	VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	edad INTEGER NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	email VARCHAR(100),
	telefono VARCHAR(20)
);

CREATE TABLE Oficina(
	codigo VARCHAR(10) PRIMARY KEY,
	direccion VARCHAR(50) NOT NULL,
	telefono VARCHAR(20) NOT NULL
);

CREATE TABLE Cuenta(
	IBAN VARCHAR(150) PRIMARY KEY,
	numero INTEGER NOT NULL,
	saldo DECIMAL(10,2) DEFAULT 0.0,
	fechaCreacion DATE NOT NULL
);

CREATE TABLE Posee(
	DNI VARCHAR(10) NOT NULL,
	IBAN VARCHAR(150) NOT NULL,
	PRIMARY KEY (DNI,IBAN),
	FOREIGN KEY (DNI) REFERENCES Cliente(DNI) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CuentaCorriente(
	oficina VARCHAR(10) REFERENCES Oficina(codigo) NOT NULL
) INHERITS (Cuenta);

CREATE TABLE CuentaAhorro(
  interes DECIMAL(3,2) NOT NULL
) INHERITS (Cuenta);


CREATE TABLE Operacion(
  codigo VARCHAR(150) NOT NULL,
	IBANOrigen VARCHAR(150) NOT NULL,
	fecha DATE NOT NULL,
	hora VARCHAR(8) NOT NULL,
	cantidad DECIMAL(10,2) NOT NULL,
	descripcion VARCHAR(400),
	PRIMARY KEY (codigo, IBANOrigen),
	FOREIGN KEY (IBANOrigen) REFERENCES Cuenta(IBAN)
);

CREATE TABLE Transferencia(
    IBANDestino VARCHAR(150) NOT NULL
) INHERITS (Operacion);

CREATE TABLE Ingreso(
    oficina VARCHAR(15),
		FOREIGN KEY (oficina) REFERENCES Oficina(codigo)
) INHERITS (Operacion);

CREATE TABLE Retirada(
    oficina VARCHAR(15), FOREIGN KEY (oficina) REFERENCES Oficina(codigo)
) INHERITS(Operacion);
